name: Formatting Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/ruff-action@v3.5.1
        with:
          options: "--check --verbose"
          src: "./src"
          version: "25.11.0"

      - run: ruff check --fix
      - run: ruff format
